# Grafana Provisioning - 数据源配置
# 自动配置数据源，无需手动添加

apiVersion: 1

datasources:
  # 主要 Prometheus 数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-main
    version: 1
    editable: false
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "300s"
      manageAlerts: true
      prometheusType: "Prometheus"
      prometheusVersion: "2.40.0"
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "jaeger-main"
          urlDisplayLabel: "View Trace"
    orgId: 1

  # Elasticsearch 日志数据源
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "mindora-*"
    uid: elasticsearch-main
    version: 1
    editable: false
    basicAuth: false
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.11.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
      includeFrozen: false
      sigV4Auth: false
    orgId: 1

  # PostgreSQL 业务数据库（只读）
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: "${POSTGRES_DB:-mindora_dev}"
    user: "${POSTGRES_USER:-mindora_user}"
    uid: postgres-main
    version: 1
    editable: false
    isDefault: false
    jsonData:
      sslmode: "disable"
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 300
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: "${POSTGRES_PASSWORD:-mindora_password_change_me}"
    orgId: 1

  # 专用Redis监控数据源
  - name: Redis Metrics
    type: prometheus  
    access: proxy
    url: http://prometheus:9090
    uid: redis-metrics
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      customQueryParameters: ""
      prometheusType: "Prometheus"
    orgId: 1

  # 专用MinIO监控数据源
  - name: MinIO Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: minio-metrics
    version: 1
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "30s"
      customQueryParameters: ""
      prometheusType: "Prometheus"
    orgId: 1

# 删除数据源配置（在数据源不存在时）
deleteDatasources:
  - name: "TestData DB"
    orgId: 1